### ISSUE TITLE
Deezer sent a non-JSON response :: 'vhost not allowed\n'

### ISSUE THREAD

**Issue by SigismundDijkstra** [SBRK/deezer-new-releases#1]
Deezer had a GUI update and now it no longer seems to work, sending out this error:

> Deezer sent a non-JSON response :: 'vhost not allowed\n'

It has given some random error messages in the past (I can't remember exactly what they said, I don't think it was this), but trying again later it worked. It's been a while and it hasn't fixed itself so I'm guessing they've changed something? 

Hope it can be fixed, I had become somewhat dependent on this.

Thanks, and thanks for this tool -- super super helpful, I wish they offered a native new releases page for followed artists like this.

**Comment by SigismundDijkstra** [comment]
Thankfully it appears to have resolved itself.

**Comment by SBRK** [comment]
Can't say I have seen this error. I still use the script daily and except for some "quota exceeded" errors that just need a refresh, I haven't seen any errors. That's good if it got resolved
